version: '3'

services:
  stability-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - SERVER_ADDR=:8080
      - LOG_LEVEL=info
      - CACHE_PATH=/app/cache
      - RATE_LIMIT=500ms
    volumes:
      - stability-cache:/app/cache

volumes:
  stability-cache: