app = "stability-go"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  LOG_LEVEL = "info"
  SERVER_ADDR = ":8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true