version: '3'

services:
  stability-proxy:
    build:
      context: ../..
      dockerfile: examples/proxy-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - CACHE_PATH=/cache
      - RATE_LIMIT=500ms
      - ALLOWED_HOSTS=
      - ADDR=:8080
    volumes:
      - stability_cache:/cache

volumes:
  stability_cache: