name = "stability-go-proxy"
main = "worker.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
usage_model = "bundled"

[vars]
STABILITY_API_KEY = ""

[build]
command = "tinygo build -o worker.wasm -target=wasm -no-debug worker.go"

[build.upload]
format = "modules"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["worker.wasm"]

# Optional KV namespace if you want to use KV for caching
# [kv_namespaces]
# binding = "STABILITY_CACHE"